# use the official python image from the dockerhub
FROM python:3.9-slim

# set the working directory
WORKDIR /app

# copy the current directory elements into the container at /app
COPY . /app

# install any needed packages specified in requirements.txt
RUN pip install Flask

# make port 5000 available to the world outside this container
EXPOSE 5000

# run app.py when container launches
CMD ["Python", "app.py"]